services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.21.0@sha256:4e1e8d98b883009cb849851857e277109c21db1c2d857ae61e14de894f2169ff
    container_name: mealie
    restart: unless-stopped
    user: ${PUID}:${PGID}
    ports:
        - "9925:9000"
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - ./data:/app/data/
    env_file:
      - .env
